name: CMake

on:
  push:
    branches: [ "main", "Asgmt7" ]
  pull_request:
    branches: [ "main", "Asgmt7" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test collision
      working-directory: ${{github.workspace}}/build/tests
      run: ./collision
    
    - name: Test local to world transformation
      working-directory: ${{github.workspace}}/build/tests
      run: ./localToWorld
    
    - name: Test if player is looking to the enemy
      working-directory: ${{github.workspace}}/build/tests
      run: ./looking
    
    - name: Test mesharea (Unity concept)
      working-directory: ${{github.workspace}}/build/tests
      run: ./mesharea
      
    - name: Test polygon
      working-directory: ${{github.workspace}}/build/tests
      run: ./polygon
    
    - name: Test reflect
      working-directory: ${{github.workspace}}/build/tests
      run: ./reflect
    
    - name: Test turrent
      working-directory: ${{github.workspace}}/build/tests
      run: ./turrent
      
    - name: Test world to local transformation
      working-directory: ${{github.workspace}}/build/tests
      run: ./worldToLocal
